# Generated by Django 4.2.4 on 2023-11-28 20:24

import datetime
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_categoria', models.CharField(max_length=50, verbose_name='Categoría Producto')),
            ],
        ),
        migrations.CreateModel(
            name='ClasificacionCostoGasto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=50, verbose_name='Clasificación Costo/Gasto')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha Nacimiento')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Insumos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_insumo', models.CharField(max_length=60, verbose_name='Nombre Insumo')),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField()),
                ('valor_inventario', models.FloatField()),
                ('costo_unitario', models.FloatField(verbose_name='Costo Unitario')),
                ('fecha_ingreso', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Ingreso')),
                ('factura_proveedor', models.CharField(max_length=50)),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proinso_app.insumos')),
            ],
        ),
        migrations.CreateModel(
            name='Medidas',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_medida', models.CharField(max_length=10, verbose_name='Tipo Medida')),
            ],
        ),
        migrations.CreateModel(
            name='Metodopago',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_metodopago', models.CharField(max_length=20, verbose_name='Metodo Pago')),
            ],
        ),
        migrations.CreateModel(
            name='TipoDocumento',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TrxComercial',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('clasificacion', models.CharField(max_length=60, verbose_name='Tipo Transaccion Comercial')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_venta', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha Venta')),
                ('fecha_entrega', models.DateTimeField(default=datetime.datetime(2023, 12, 5, 20, 24, 1, 914823, tzinfo=datetime.timezone.utc), verbose_name='Fecha Instalacion')),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('id_asesor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.empleado')),
                ('id_cliente', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.cliente')),
                ('id_metodopago', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.metodopago')),
                ('id_trx_comercial', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.trxcomercial')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategoria',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom_subcategoria', models.CharField(max_length=50, verbose_name='Subcategoria_Producto')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proinso_app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('apellido', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=250, verbose_name='Email')),
                ('fecha_ingreso', models.DateTimeField(auto_now_add=True)),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.tipodocumento')),
            ],
        ),
        migrations.CreateModel(
            name='nomina',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valor_pago', models.IntegerField(verbose_name='Valor a Pagar')),
                ('fecha_pago', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('id_empleado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.empleado')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsVenta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad', models.FloatField(verbose_name='Cantidad Material')),
                ('id_inventario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.inventario')),
                ('id_venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proinso_app.venta')),
            ],
        ),
        migrations.AddField(
            model_name='inventario',
            name='id_proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.proveedor'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='id_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proinso_app.medidas'),
        ),
        migrations.AddField(
            model_name='insumos',
            name='id_subcategoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proinso_app.subcategoria'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.tipodocumento'),
        ),
        migrations.CreateModel(
            name='CostosGastos',
            fields=[
                ('id_factura', models.AutoField(primary_key=True, serialize=False)),
                ('valor', models.FloatField()),
                ('fecha_transaccion', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Transaccion')),
                ('comentario', models.CharField(blank=True, max_length=300)),
                ('id_clasificacion_costogasto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.clasificacioncostogasto')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='tipo_documento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='proinso_app.tipodocumento'),
        ),
    ]
