# Generated by Django 4.2.4 on 2023-11-29 21:32

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proinso_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='id',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 21, 32, 3, 697540, tzinfo=datetime.timezone.utc), verbose_name='Fecha Instalacion'),
        ),
    ]
