# Generated by Django 4.2.4 on 2023-11-29 21:53

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('proinso_app', '0003_alter_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 6, 21, 53, 37, 833339, tzinfo=datetime.timezone.utc), verbose_name='Fecha Instalacion'),
        ),
    ]
