# Generated by Django 4.2.4 on 2023-12-04 23:34

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proinso_app', '0006_empleado_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoCargo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cargo', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(1993, 12, 11, 23, 34, 25, 120456, tzinfo=datetime.timezone.utc), verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(1993, 12, 11, 23, 34, 25, 123355, tzinfo=datetime.timezone.utc), verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 11, 23, 34, 25, 132031, tzinfo=datetime.timezone.utc), verbose_name='Fecha Instalacion'),
        ),
        migrations.AddField(
            model_name='empleado',
            name='tipo_cargo',
            field=models.ForeignKey(default=8, on_delete=django.db.models.deletion.CASCADE, to='proinso_app.tipocargo'),
        ),
    ]
