# Generated by Django 4.2.4 on 2023-12-07 16:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proinso_app', '0007_tipocargo_alter_cliente_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='itemsventa',
            old_name='id_inventario',
            new_name='id_insumo',
        ),
        migrations.AlterField(
            model_name='cliente',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(1993, 12, 14, 16, 12, 15, 752741, tzinfo=datetime.timezone.utc), verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.datetime(1993, 12, 14, 16, 12, 15, 754808, tzinfo=datetime.timezone.utc), verbose_name='Fecha Nacimiento'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha_entrega',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 14, 16, 12, 15, 760782, tzinfo=datetime.timezone.utc), verbose_name='Fecha Instalacion'),
        ),
    ]
